language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

sudo: false

script: phpunit --coverage-clover=coverage.clover

matrix:
  fast_finish: true
